config/routes.rb
Gib::Application.routes.draw do
  devise_for :admins

  devise_for :users

  resources :subforums
  resources :topics
  resources :posts

  root :to => "home#index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me
end

app/models/post.rb
class Post < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :topic
  
  validates_presence_of :message, :user_id, :topic_id
  
end

app/models/subforum.rb
class Subforum < ActiveRecord::Base
  
  PRIVATE = ['0','1']
  
  has_many :topics
  validates_presence_of :title, :description, :is_private
  
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :subforum
  
  has_many :posts
  
  validates_presence_of :title, :descrpition, :user_id, :subforum_id
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me
  
  has_many :topics
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if user_signed_in? | admin_signed_in?
      @subforums = Subforum.all
    else
      @subforums = Subforum.where('is_private = ?', 0)
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  respond_to :html, :json
  
  before_filter :find_post, :except => ['index', 'new', 'create']
  before_filter :authenticate_user!, :except => ['show']
  before_filter :authenticate_admin!, :except => ['show', 'new', 'create']
  
  def index
    @posts = Post.all
    #This of course needs to be fixed
  end
  
  def show
    respond_with @post
  end
  
  def new
    @post = Post.new
    @post.topic_id = params[:topic_id]

    respond_with @post
  end
  
  def create
    @post = Post.new(params[:post])
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = "Successfully replied to topic."
      #respond_with @post, :location => topic_path(@post.topic)
      respond_with @topic, :location => topic_url(@post.topic)
    else
      flash[:alert] = "Failed to create post."
      render :action => :new
    end
  end
  
  def edit
    respond_with @post
  end
  
  def update
    if @post.update_attributes(params[:post])
      flash[:notice] = "Successfully edited post."
      respond_with @posts, :location => posts_path
    else
      flash[:alert] = "Failed to edit post."
      render :action => :edit
    end
  end
  
  def destroy
    flash[:notice] = 'Successfully removed post.' if @post.delete
    respond_with @post
  end
  
  private
  
  def find_post
    @post = Post.find(params[:id])
  end
  
end

app/controllers/subforums_controller.rb
class SubforumsController < ApplicationController
  
  respond_to :html, :json
  
  before_filter :find_subforum, :except => ['index', 'new', 'create']
  before_filter :find_topics, :except => ['index', 'new', 'create']
  before_filter :authenticate_user!, :except => ['show']
  before_filter :authenticate_admin!, :except => ['show']
  
  def index
    @subforums = Subforum.all
  end
  
  def show
    respond_with @subforum
  end
  
  def new
    @subforum = Subforum.new
    respond_with @subforum
  end
  
  def create
    @subforum = Subforum.new(params[:subforum])
    if @subforum.save
      flash[:notice] = "Successfully created a new subforum."
      respond_with @subforum, :location => subforums_path
    else
      flash[:alert] = "Failed to create a new subforum."
      render :action => :new
    end
  end
  
  def edit
    respond_with @subforum
  end
  
  def update
    if @subforum.update_attributes(params[:subforum])
      flash[:notice] = "Successfully updated Subforum."
      respond_with @subforum, :location => subforums_path
    else
      flash[:alert] = "Failed to update Subforum."
      render :action => :edit
    end
  end
  
  def destroy
    flash[:notice] = 'Successfully removed subforum.' if @subforum.delete
    respond_with @subforum
  end
  
  private
  
  def find_subforum
    @subforum = Subforum.find(params[:id])
  end
  
  def find_topics
    @topics = @subforum.topics
  end
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  respond_to :html, :json
  
  before_filter :find_topic, :except => ['index', 'new', 'create']
  before_filter :find_posts, :except => ['index', 'new', 'create']
  before_filter :authenticate_user!, :except => ['show']
  before_filter :authenticate_admin!, :except => ['show', 'new', 'create']
  
  def index
    @topics = Topic.all
    #This of course needs to be fixed
  end
  
  def show
    respond_with @topic
  end
  
  def new
    @topic = Topic.new
    @topic.subforum_id = params[:subforum_id]

    respond_with @topic
  end
  
  def create
    @topic = Topic.new(params[:topic])
    @topic.user_id = current_user.id
    if @topic.save
      flash[:notice] = "Successfully created topic."
      respond_with @topic, :location => new_post_path(:topic_id => @topic.id)
    else
      flash[:alert] = "Failed to create topic."
      render :action => :new
    end
  end
  
  def edit
    respond_with @topic
  end
  
  def update
    if @topic.update_attributes(params[:topic])
      flash[:notice] = "Successfully updated topic."
      respond_with @topic, :location => topics_path
    else
      flash[:alert] = "Failed to update topic."
      render :action => :edit
    end
  end
  
  def destroy
    flash[:notice] = 'Successfully removed topic.' if @topic.delete
    respond_with @topic
  end
  
  private
  
  def find_topic
    @topic = Topic.find(params[:id])
  end
  
  def find_posts
    @posts = @topic.posts.paginate :page => params[:page], :order => 'created_at ASC', :per_page => 10
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/subforums_helper.rb
module SubforumsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/home/_subforum.html.haml
#home_subforum
  %li
    .title
      = link_to "#{subforum.title}", subforum_path(subforum)
    .description
      = subforum.description

app/views/home/index.html.haml
%ul
  = render :partial => 'subforum', :collection => @subforums

app/views/layouts/application.html.haml
!!!
%head
  %title Gib
  = stylesheet_link_tag :all
  = javascript_include_tag :defaults
  = csrf_meta_tag
%body
  #user_cp
    %ul
      = render :partial => '/shared/user_cp'
  .clear
  #main_container
    = yield
  - if admin_signed_in?  
    #admin_cp
      = render :partial => '/shared/admin_cp'

app/views/posts/_form.html.haml
= form_for(@post) do |f|
  = f.error_messages
  %fieldset
    %legend
      Information
    %p
      = f.label :message
      %br
      = f.text_area :message
    
    =f.hidden_field :topic_id
  %p
    = f.submit
    or
    %a.cancel_link{ :href => topic_path(@post.topic) } Cancel

app/views/posts/_post.html.haml
%li
  %p
    = post.user.username
  %p
    = post.message
  %p
    = link_to 'Edit', edit_post_path(post)
    = "/"
    = link_to 'Delete', post_path(post), :method => 'delete', :confirm => "Are you sure you want to delete this post?"

app/views/posts/edit.html.haml
%h3
  Edit Post

= render :partial => 'form'

app/views/posts/index.html.haml
%ul
  = render :partial => 'post', :collection => @posts

app/views/posts/new.html.haml
= render :partial => 'form'

app/views/posts/show.html.haml
%p
  = @post.user.username
%p
  = @post.message

= link_to "Back to topics", topics_path

app/views/shared/_admin_cp.html.haml
%ul
  %li
    Signed in as admin:
    = current_admin.username
  %li
    = link_to 'Subforum Management', subforums_path
  %li
    = link_to 'Topic Management', topics_path
  %li
    = link_to 'Post Management', posts_path
  %li
    = link_to 'Logout Admin Account', destroy_admin_session_path

app/views/shared/_user_cp.html.haml
- if user_signed_in?
  %li
    Signed in as
    %em
      = current_user.username
- if user_signed_in?
  %li
    = link_to('Logout', destroy_user_session_path)
- else
  %li
    = link_to('Login', new_user_session_path)
    
- if user_signed_in?
  %li
    = link_to('Edit Registration', edit_user_registration_path)
- else
  %li
    = link_to('Register', new_user_registration_path)

app/views/subforums/_form.html.haml
= form_for(@subforum) do |f|
  = f.error_messages
  %fieldset
    %legend
      Information
    %p
      = f.label :title
      %br
      = f.text_field :title
    %p
      = f.label :description
      %br
      = f.text_area :description
    %p
      = f.label :is_private
      %br
      = f.select :is_private, Subforum::PRIVATE, :prompt => "Private?"
  %p
    = f.submit
    or
    %a.cancel_link{ :href => subforums_path } Cancel
  

app/views/subforums/_subforum.html.haml
%li
  %p
    = subforum.title
  %p
    = subforum.description
  %p
    = link_to 'Edit', edit_subforum_path(subforum)
    = "/"
    = link_to 'Delete', subforum_path(subforum), :method => 'delete', :confirm => "Are you sure you want to delete #{subforum.title}"

app/views/subforums/_topic.html.haml
%li
  .topic_title
    = link_to "#{topic.title}", topic_path(topic)
  .topic_description
    = topic.description

app/views/subforums/edit.html.haml
%h3
  Edit 
  = @subforum.title

= render :partial => 'form'

app/views/subforums/index.html.haml
%ul
  = render :partial => 'subforum', :collection => @subforums
  
= link_to 'Add a Subforum', new_subforum_path

app/views/subforums/show.html.haml
#title_container
  .title
    = @subforum.title
  .description
    = @subforum.description
    
#topics_container
  %ul    
    = render :partial => 'topic', :collection => @topics
    
#subforum_actions
  = link_to 'Post a new Topic', new_topic_path(:subforum_id => @subforum.id)
  = link_to "Back to subforums", root_path
.clear

app/views/topics/_form.html.haml
= form_for(@topic) do |f|
  = f.error_messages
  %fieldset
    %legend
      Information
    %p
      = f.label :title
      %br
      = f.text_field :title
    %p
      = f.label :description
      %br
      = f.text_area :description
      
    = f.hidden_field :subforum_id
  %p
    = f.submit
    or
    %a.cancel_link{ :href => subforum_path(@topic.subforum) } Cancel

app/views/topics/_post.html.haml
%li
  #post_container
    #user_box
      .post_username
        = post.user.username
      = post.created_at.strftime( '%b %d, %Y %I:%M' )
    #message_box
      .post_message
        = post.message
        
    .clear
    

app/views/topics/_topic.html.haml
%li
  %p
    = topic.title
  %p
    = topic.description
  %p
    = link_to 'Edit', edit_topic_path(topic)
    = "/"
    = link_to 'Delete', topic_path(topic), :method => 'delete', :confirm => "Are you sure you want to delete #{topic.title}"

app/views/topics/edit.html.haml
%h3
  Edit 
  = @topic.title

= render :partial => 'form'

app/views/topics/index.html.haml
%ul
  = render :partial => 'topic', :collection => @topics
  
= link_to 'Add a topic', new_topic_path

app/views/topics/show.html.haml
#title_container
  .title
    = @topic.title
  .description
    = @topic.description

#posts_container
  %ul    
    = render :partial => 'post', :collection => @posts
    
#subforum_actions
  = will_paginate @posts
  = link_to 'Post a reply', new_post_path(:topic_id => @topic.id)
  = link_to "Back to topics", subforum_path(@topic.subforum)
.clear